### ISSUE TITLE
Silver Sky modcats

### ISSUE THREAD

**Issue by kilsen** [DChandlerP/ModCatDecoder#11]
I have a Silver Sky and the modcat seems to be quite different from the other PRS models.

The modcat on my hangtag (near the UPC code) is: J1JS37_J4_JGJ_—
(Those are three consecutive '-' characters at the end.)
The color of my Silver Sky is tungsten.
It's entirely possible that the modcat on the hangtag is not the full complete modcat in my case.

I found a few modcats online on Reverb listings:

J1A2-MJISJ_JGJ/J5/13W - Dodgem Blue
J1A2-MJISJ_JGJ/J7 - MocSand
J1A2-MJISJ_JGJ/J6 - Golden Mesa
J1A2-MJISJ_JGJ-J1 - Onyx

So it's looking like the J# near the end indicates the color code of the John Mayer Silver Sky. So far it seems:
1 = Onyx
4 = Tungsten
5 = Dodgem Blue
6 = Golden Mesa
7 = Moc Sand

So it's probably the case that 8 is probably Orion Green, and 2 and 3 are Frost and Horizon (though I'm not sure which is which).

That's as much as I was able to find out so far.

**Comment by DChandlerP** [comment]
I have a Horizon myself J3 is Horizon so J2 is probably frost!  I have that /13w at the end of mine too. Any idea what that is?

**Comment by DChandlerP** [comment]
I updated this partially but didn't have enough information to go on currently for me to update it further.
