### ISSUE TITLE
Custom 24 2019

### ISSUE THREAD

**Issue by karledwards1** [DChandlerP/ModCatDecoder#12]
CUM4FNHTI63_5-5V

2019 Custom 24

**Comment by DChandlerP** [comment]
My apologies for not seeing this sooner. I might be able to add this one but I'd need more information. If you have shots of the hangtag and the original MODCAT that would be a help.

**Comment by DChandlerP** [comment]
I'm going to close this but if you have information on the specs of your guitar that would help me decode what information we don't have from the MODCAT I'll happily add it into the file where we keep all the model information.
