### ISSUE TITLE
Mira Core 2009 color not listed

### ISSUE THREAD

**Issue by Davidfranom** [DChandlerP/ModCatDecoder#26]
For the Modcat: MIH4--HSILS_SC_N4-4J
wich belongs to a Mira from 2009, the initials 'SC' stand for 'Sinful Cinnamon' which was a limited run color for that very year.

**Comment by DChandlerP** [comment]
Fixed! Sorry I was slow, I couldn't confirm your modcat code. I eventually just decided to accept it as is.
