### ISSUE TITLE
Neck Wood: Couldn't find Neck Wood for D   and can somebody tell me the code for the bird inlay?

### ISSUE THREAD

**Issue by pogguitars** [DChandlerP/ModCatDecoder#27]
I want to know if D is like Indian rosewood and why PRS use I also for Indian Rosewood.
Can somebody tell me the code for the bird inlay?

**Comment by DChandlerP** [comment]
Unfortunately I need examples of the codes to decipher them.

**Comment by pogguitars** [comment]
Do you want the actual photos of the code?

Thanks for the mod cad decoder, this is the best thing I discover this year on internet!

peace,

pog

________________________________
De : David Chandler Prince ***@***.***>
Envoyé : 19 septembre 2024 14:21
À : DChandlerP/ModCatDecoder ***@***.***>
Cc : pogguitars ***@***.***>; Author ***@***.***>
Objet : Re: [DChandlerP/ModCatDecoder] Neck Wood: Couldn't find Neck Wood for D and can somebody tell me the code for the bird inlay? (Issue #27)


Unfortunately I need examples of the codes to decipher them.
