### ISSUE TITLE
Experience 2018 Paul's Guitar

### ISSUE THREAD

**Issue by kilsen** [DChandlerP/ModCatDecoder#5]
I have one of the limited edition Experience 2018 Paul's Guitar models. There were only 100 sold (50 in the US, 50 outside).

The MODCAT is: EXM2FPCFXXS_DD_HB-BA

Here are the specs: https://www.prsguitars.com/index.php/electrics/model/experience_prs_2018_pauls_guitar

I think this might reveal some issues with the modcat codes. Specifically, I think that elecA should be "Paul's" rather than "Bass." Also, treblepuB and basspuB should be "408 or Paul's" rather than "408 or Bass." HOWEVER, we probably need more modcat examples from other Paul's Guitar models to know for sure.

colorDD is apparently Black Gold Nitro and fingerboardX is apparently Ziricote. I'm not sure why the neck wood code is X because the specs say it's a Mahogany neck.

modelEX must refer specifically to this Experience 2018 model.

topGrade P could mean Private Stock since the specs indicate that it's got a "Private Stock Carved Figured Maple" top.

**Comment by DChandlerP** [comment]
It's kind of hard not being a PRS employee and having someone to just ask!

**Comment by DChandlerP** [comment]
I've updated it so yours will now work. I made notes in comments for the new and changed entries that this is still speculative.
